version: "3.8"

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3004:3004'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'