version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
  eslint:
    stage: lint
    script:
      # Install eslint
      - |
        npm install eslint \
        eslint-config-airbnb \
        eslint-plugin-flowtype \ # Any ideas on what I might want to do next?
        eslint-plugin-import \
        eslint-plugin-jsx-a11y \
        eslint-plugin-react
      # Run eslint
      - node_modules/eslint/bin/eslint.js .